# Generated by Django 5.2.7 on 2025-11-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="gpa",
        ),
    ]
