# Generated by Django 5.2.7 on 2025-11-06 09:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_student_gpa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Learner Feedback",
                "verbose_name_plural": "Learner Feedbacks",
            },
        ),
        migrations.RemoveField(
            model_name="tutorapplication",
            name="teach_to",
        ),
        migrations.AddField(
            model_name="feedback",
            name="attend_again",
            field=models.BooleanField(
                default=True,
                verbose_name="Would you attend another session with this tutor?",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="explanation_rating",
            field=models.IntegerField(
                default=3,
                help_text="1 (Poor) to 5 (Excellent)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="How would you rate your tutor's explanation skills?",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked session if available",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks",
                to="core.session",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="usefulness_rating",
            field=models.IntegerField(
                default=3,
                help_text="1 (Not useful) to 5 (Very useful)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="How useful was the session for your understanding?",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="well_organized",
            field=models.BooleanField(
                default=True,
                verbose_name="Was the session well-organized and time-managed?",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="has_disciplinary_warning",
            field=models.BooleanField(
                default=False, help_text="Has active disciplinary warnings"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="study_year",
            field=models.ForeignKey(
                blank=True,
                help_text="Study year (same as year, for compatibility)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_students",
                to="core.year",
            ),
        ),
        migrations.AddField(
            model_name="tutorapplication",
            name="confidence_rating",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=3,
                help_text="1 (Low) to 5 (High)",
                verbose_name="Rate your confidence in teaching a small group",
            ),
        ),
        migrations.AddField(
            model_name="tutorapplication",
            name="consent",
            field=models.BooleanField(
                default=False,
                verbose_name="I consent that all information is accurate, and I agree that my PAL participation hours may appear on the AGU Skills Record.",
            ),
        ),
        migrations.AddField(
            model_name="tutorapplication",
            name="max_sessions_per_week",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum sessions/hours per week",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="tutorapplication",
            name="motivation",
            field=models.TextField(
                default="",
                help_text="Short open answer",
                verbose_name="Why do you want to be a PAL tutor?",
            ),
        ),
        migrations.AddField(
            model_name="tutorapplication",
            name="preferred_days",
            field=models.CharField(
                blank=True, help_text="e.g., Monday, Wednesday", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="tutorapplication",
            name="preferred_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("On-campus", "On-campus"),
                    ("Online", "Online"),
                    ("Hybrid", "Hybrid"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tutorapplication",
            name="preferred_times",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Morning", "Morning"),
                    ("Afternoon", "Afternoon"),
                    ("Evening", "Evening"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="comments",
            field=models.TextField(
                blank=True, verbose_name="How could this session be improved?"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(
                blank=True,
                help_text="Overall rating (1-5)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="session_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Auto-documented date/time"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="topic",
            field=models.CharField(
                max_length=200, verbose_name="Title/Topic of the session"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="tutor",
            field=models.ForeignKey(
                limit_choices_to={"tutor_applications__status": "Approved"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Name of the Tutor",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.year",
                verbose_name="Learner's year",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="year",
            field=models.ForeignKey(
                help_text="Current year of study",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="core.year",
            ),
        ),
        migrations.AlterField(
            model_name="tutorapplication",
            name="engaged_in_pal",
            field=models.CharField(
                choices=[
                    ("tutor", "Yes, as a tutor"),
                    ("learner", "Yes, as a learner"),
                    ("both", "Yes, as both"),
                    ("solo", "No, I am a solo learner!"),
                ],
                default="solo",
                max_length=20,
                verbose_name="Have you been engaged in PAL?",
            ),
        ),
        migrations.AlterField(
            model_name="tutorapplication",
            name="gpa",
            field=models.FloatField(
                default=3.0,
                help_text="GPA (0.0 - 4.0)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(4.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tutorapplication",
            name="interested_as_tutor",
            field=models.BooleanField(
                default=False,
                verbose_name="Interested to act as PAL tutors and teach to your peers or near-peers?",
            ),
        ),
        migrations.AlterField(
            model_name="tutorapplication",
            name="mobile",
            field=models.CharField(
                blank=True,
                help_text="Exactly 8 digits, no characters",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mobile number must be exactly 8 digits with no characters.",
                        regex="^\\d{8}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tutorapplication",
            name="suggestions",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="What else do you like to see in the PAL program at AGU?",
            ),
        ),
        migrations.AlterField(
            model_name="tutorapplication",
            name="wants_certificate",
            field=models.BooleanField(
                default=False,
                verbose_name="Like to receive a certificate to acknowledge contribution?",
            ),
        ),
        migrations.AlterField(
            model_name="tutorapplication",
            name="wants_training",
            field=models.BooleanField(
                default=False,
                verbose_name="Interested to get training in session planning as PAL tutors?",
            ),
        ),
        migrations.AlterField(
            model_name="tutorapplication",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.year",
                verbose_name="Year of study",
            ),
        ),
        migrations.CreateModel(
            name="EvaluationYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        help_text="e.g., 2025-26", max_length=10, unique=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Only one year can be active at a time"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "programs",
                    models.ManyToManyField(
                        blank=True, related_name="evaluation_years", to="core.program"
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluation Year",
                "verbose_name_plural": "Evaluation Years",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="session",
            name="evaluation_year",
            field=models.ForeignKey(
                blank=True,
                help_text="Academic year for this session",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="core.evaluationyear",
            ),
        ),
    ]
