# Generated by Django 5.2.7 on 2025-11-06 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_feedback_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorapplication",
            name="gpa",
            field=models.FloatField(
                blank=True,
                help_text="GPA (0.0 - 4.0)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(4.0),
                ],
            ),
        ),
    ]
